# GitHub Actions workflow file for deploying Terraform configurations
name: payment-processor-terraform-deployment-pipeline

on:
  push:
    branches: [main]
    paths:
      - 'common-infrastructure-setup/**'
  pull_request:
    branches: [main]
    paths:
      - 'common-infrastructure-setup/**'

# Top-level default permissions
permissions:
  contents: read
  id-token: write

jobs:
  secret_detection:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for secret detection
      - name: Run Gitleaks for secret detection
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform_validate:
    name: Terraform Validate
    needs: secret_detection
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./common-infrastructure-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.7.5

      - name: Cache Terraform Plugins #caching the terraform providers to speed up the workflow
        uses: actions/cache@v4
        with:
          path: |
            ./common-infrastructure-setup/.terraform/providers
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('common-infrastructure-setup/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

  terraform_plan:
    name: Terraform Plan
    needs: terraform_validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # Explicitly set at job level
    defaults:
      run:
        working-directory: ./common-infrastructure-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.7.5
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-file
          path: common-infrastructure-setup/tfplan

  terraform_apply:
    name: Terraform Apply
    needs: terraform_plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # Explicitly set at job level
    defaults:
      run:
        working-directory: ./common-infrastructure-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Terraform Init
        run: terraform init -input=false
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-plan-file
          path: common-infrastructure-setup/

      - name: Terraform Apply
        run: terraform apply -input=false tfplan